#!/usr/bin/env bash
# Monthly data refresh: re-collect what can have changed, rebuild, review cases, publish, test, report, commit.
#
#   scripts/refresh.sh            # everything up to a local commit (review it, then git push)
#   scripts/refresh.sh --push     # ... and push (GitHub Pages redeploys automatically)
#   scripts/refresh.sh --offline  # skip collection; rebuild + publish from the existing caches
#   scripts/refresh.sh --no-commit  # stop before committing (dry run)
#
# Run from India: the government portals may not answer requests from elsewhere. Collection is polite (about one
# request per second, cached); a typical monthly run makes ~600-900 requests (15-30 min) and needs tesseract for OCR.
set -euo pipefail
cd "$(dirname "$0")/.."
PY=.venv/bin/python
PUSH=0; OFFLINE=0; COMMIT=1
for a in "$@"; do case "$a" in --push) PUSH=1 ;; --offline) OFFLINE=1 ;; --no-commit) COMMIT=0 ;; *) echo "unknown option $a"; exit 2 ;; esac; done
STAMP=$(date +%Y-%m-%d)
LOGDIR=data/refresh_logs; mkdir -p "$LOGDIR"; LOG="$LOGDIR/$STAMP.log"
step() { echo; echo "== $*" | tee -a "$LOG"; }
run()  { "$@" >>"$LOG" 2>&1 || { echo "FAILED: $* (see $LOG)"; exit 1; }; }

[ -n "$(git status --porcelain -- app ingest tests)" ] && { echo "Uncommitted code changes in app/ ingest/ tests/ — commit or stash them first."; exit 1; }
cp data/public/koramangala_public.db "$LOGDIR/previous.db" 2>/dev/null && chmod u+w "$LOGDIR/previous.db" || true

if [ "$OFFLINE" = 0 ]; then
  step "1/5 collect: KPPP tenders (awards still pending are re-checked) and tender documents"
  run $PY -m ingest.fetch_kppp
  run $PY -m ingest.fetch_kppp_docs
  step "    collect: IFMS payment grid (open quarters re-fetched)"
  run $PY -m ingest.discover_bbmp
  step "    collect: IFMS bills for new jobs, active jobs and unpaid bills"
  run $PY -m ingest.fetch_bbmp_direct --refresh-active --no-files
fi

step "2/5 build + quantities + extensions of time"
run $PY -m ingest.build
if [ "$OFFLINE" = 0 ]; then run $PY -m ingest.quantities; run $PY -m ingest.eot; else run $PY -m ingest.quantities --no-fetch; run $PY -m ingest.eot --no-fetch; fi
run $PY -m ingest.build

step "3/5 case review (documents for candidate cases, then the cases)"
if [ "$OFFLINE" = 0 ]; then run $PY -m ingest.case_evidence; else run $PY -m ingest.case_evidence --no-fetch; fi
run $PY -m ingest.cases
run $PY -m ingest.build
run $PY -m experiments.phase5_metrics

step "4/5 publish (scrub + read-only DB + dataset), test, static export"
run $PY -m ingest.publish
run $PY -m pytest -q
run $PY -m app.freeze --base /bengaluru-public-works/ --out site

step "5/5 what changed"
if [ -f "$LOGDIR/previous.db" ]; then $PY -m ingest.changes "$LOGDIR/previous.db" data/public/koramangala_public.db --log | tee -a "$LOG"; fi

[ "$COMMIT" = 0 ] && { echo "Dry run: nothing committed. Review with: git status"; exit 0; }
git add data/public CHANGELOG_DATA.md cases CASE_INDEX.md
if git diff --cached --quiet; then echo "No data changes to commit."; exit 0; fi
git commit -q -m "Data refresh $STAMP" -m "Generated by scripts/refresh.sh; see CHANGELOG_DATA.md."
echo "Committed: $(git log --oneline -1)"
if [ "$PUSH" = 1 ]; then git push -q origin main && echo "Pushed; GitHub Pages will redeploy in ~1 minute."; else echo "Review, then: git push"; fi
